name: Notify of issues resolved in latest Zulip Cloud deploy

on:
  push:
    branches:
      - zulip-cloud-current
  workflow_dispatch:
    inputs:
      before:
        description: "Old commit-ish"
        required: true
      after:
        description: "New commit-ish"
        required: true
      stream:
        description: "Stream to send to"
        default: "zulip cloud"
      topic:
        description: "Topic to send to"
        default: "latest deploy"

permissions:
  contents: read # Read repo contents
  issues: read # Read existing repo issues
  pull-requests: read # Read existing pull requests

jobs:
  build-messages:
    name: "Build messages"
    runs-on: ubuntu-slim
    outputs:
      filenames: ${{ steps.set-matrix.outputs.filenames }}
    concurrency:
      group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install uv
        run: |
          ./scripts/lib/install-uv

      - name: Generate list of resolved issues
        id: generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE: ${{ inputs.before || github.event.before }}
          HEAD: ${{ inputs.after || github.event.after }}
        run: |
          set -o pipefail

          mkdir closed-by-commits-output
          ./tools/closed-by-commits "$BASE" "$HEAD" \
            | perl -ple 'undef $/;s/\n\n/\x00/g' \
            | split -t '\0' -C 8000 -d - closed-by-commits-output/message-
          perl -pi -e 's/\00/\n\n/g' closed-by-commits-output/message-*

      - name: Upload messages as artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: closed-by-commits-output
          path: closed-by-commits-output/

      - name: Store filename list for matrix
        id: set-matrix
        run: |
          cd closed-by-commits-output/
          echo "filenames=$(ls | jq -Rnc '[inputs]')" >> $GITHUB_OUTPUT

  send-messages:
    name: "Send messages"
    needs: build-messages
    runs-on: ubuntu-slim
    strategy:
      max-parallel: 1
      matrix:
        filename: ${{ fromJson(needs.build-messages.outputs.filenames) }}
    if: ${{ success() && github.repository == 'zulip/zulip' }}
    concurrency:
      group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
      cancel-in-progress: true
    steps:
      - name: Download messages as artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: closed-by-commits-output
          path: closed-by-commits-output/

      - name: Read message contents
        id: read-file
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat "closed-by-commits-output/$FILENAME" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          FILENAME: ${{ matrix.filename }}

      - name: Send to Zulip
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_BOT_KEY }}
          email: "github-actions-bot@chat.zulip.org"
          organization-url: "https://chat.zulip.org"
          to: "${{ inputs.stream || 'zulip cloud' }}"
          topic: "${{ inputs.topic || 'latest deploy' }}"
          type: "stream"
          content: ${{ steps.read-file.outputs.content }}
